wifi_attack.py: WLAN Adapter
ble_crasher.py: BLE Adapter
rfid_cloner.py: Flipper Zero
ota_firmware_injector.py: OTA Interceptor
jtag_auto_interface.py: JTAG Probe
uart_extractor.py: UART Serial Interface
dns_c2.py: DNS Resolver
