robots:
  - name: Bot01
    ip: 192.168.0.10
    mac: AA:BB:CC:DD:EE:01
    location: Garden Area
    protocols: [wifi, ble]
    tags: [irrigation, perimeter]
    notes: Primary watering bot

  - name: Sensor-Cam-A
    ip: 192.168.0.20
    mac: AA:BB:CC:DD:EE:02
    location: North Fence
    protocols: [rtsp, wifi]
    tags: [camera, motion, rtsp]
    notes: RTSP-enabled motion camera

  - name: HVAC-Unit01
    ip: 192.168.0.30
    mac: AA:BB:CC:DD:EE:03
    location: Shed
    protocols: [modbus, http]
    tags: [hvac, temperature]
    notes: Exposed HVAC panel

  - name: Controller-Z
    ip: 192.168.0.40
    mac: AA:BB:CC:DD:EE:04
    location: Control Room
    protocols: [zigbee, mqtt]
    tags: [core, gateway]
    notes: Zigbee hub controller with MQTT broker

defaults:
  timeout: 5
  retries: 2
  stealth_mode: true
